#!/usr/bin/env bash
# adds custom mappings to the host file

sudo cp /etc/hosts /etc/hosts.bak
sudo bash -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

sudo service systemd-resolved restart
